// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: imsto.proto

package impb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey  string `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`   // APIKey
	Uri     string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`         // full URI of image
	Referer string `protobuf:"bytes,3,opt,name=referer,proto3" json:"referer,omitempty"` // special referer of request
	Roof    string `protobuf:"bytes,4,opt,name=roof,proto3" json:"roof,omitempty"`       // section name
	UserID  int64  `protobuf:"varint,5,opt,name=userID,proto3" json:"userID,omitempty"`  // user ID
	SizeOp  string `protobuf:"bytes,6,opt,name=sizeOp,proto3" json:"sizeOp,omitempty"`   // size op
}

func (x *FetchInput) Reset() {
	*x = FetchInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imsto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchInput) ProtoMessage() {}

func (x *FetchInput) ProtoReflect() protoreflect.Message {
	mi := &file_imsto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchInput.ProtoReflect.Descriptor instead.
func (*FetchInput) Descriptor() ([]byte, []int) {
	return file_imsto_proto_rawDescGZIP(), []int{0}
}

func (x *FetchInput) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *FetchInput) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *FetchInput) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

func (x *FetchInput) GetRoof() string {
	if x != nil {
		return x.Roof
	}
	return ""
}

func (x *FetchInput) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *FetchInput) GetSizeOp() string {
	if x != nil {
		return x.SizeOp
	}
	return ""
}

type ImageInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey string `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`  // APIKey
	Image  []byte `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`    // Image Binary
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`      // FileName
	Roof   string `protobuf:"bytes,4,opt,name=roof,proto3" json:"roof,omitempty"`      // section name
	UserID int64  `protobuf:"varint,5,opt,name=userID,proto3" json:"userID,omitempty"` // user ID
	SizeOp string `protobuf:"bytes,6,opt,name=sizeOp,proto3" json:"sizeOp,omitempty"`  // size op
}

func (x *ImageInput) Reset() {
	*x = ImageInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imsto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInput) ProtoMessage() {}

func (x *ImageInput) ProtoReflect() protoreflect.Message {
	mi := &file_imsto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInput.ProtoReflect.Descriptor instead.
func (*ImageInput) Descriptor() ([]byte, []int) {
	return file_imsto_proto_rawDescGZIP(), []int{1}
}

func (x *ImageInput) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ImageInput) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ImageInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageInput) GetRoof() string {
	if x != nil {
		return x.Roof
	}
	return ""
}

func (x *ImageInput) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ImageInput) GetSizeOp() string {
	if x != nil {
		return x.SizeOp
	}
	return ""
}

type ImageMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width   int32  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`     // 宽度
	Height  int32  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`   // 高度
	Quality int32  `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"` // 质量（JPEG|WebP）
	Size    int32  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`       // 大小
	Ext     string `protobuf:"bytes,5,opt,name=ext,proto3" json:"ext,omitempty"`          // 扩展名
	Mime    string `protobuf:"bytes,6,opt,name=mime,proto3" json:"mime,omitempty"`        // Mime type
}

func (x *ImageMeta) Reset() {
	*x = ImageMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imsto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMeta) ProtoMessage() {}

func (x *ImageMeta) ProtoReflect() protoreflect.Message {
	mi := &file_imsto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMeta.ProtoReflect.Descriptor instead.
func (*ImageMeta) Descriptor() ([]byte, []int) {
	return file_imsto_proto_rawDescGZIP(), []int{2}
}

func (x *ImageMeta) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageMeta) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageMeta) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *ImageMeta) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImageMeta) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *ImageMeta) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

type ImageOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string     `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // 路径 id.ext
	Uri  string     `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`   // URI 地址
	Host string     `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"` // 主机名，取自 stagHost
	ID   string     `protobuf:"bytes,4,opt,name=ID,proto3" json:"ID,omitempty"`     // ID 编码
	Meta *ImageMeta `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"` // 图片 Meta
}

func (x *ImageOutput) Reset() {
	*x = ImageOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imsto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageOutput) ProtoMessage() {}

func (x *ImageOutput) ProtoReflect() protoreflect.Message {
	mi := &file_imsto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageOutput.ProtoReflect.Descriptor instead.
func (*ImageOutput) Descriptor() ([]byte, []int) {
	return file_imsto_proto_rawDescGZIP(), []int{3}
}

func (x *ImageOutput) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ImageOutput) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ImageOutput) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ImageOutput) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ImageOutput) GetMeta() *ImageMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_imsto_proto protoreflect.FileDescriptor

var file_imsto_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x69, 0x6d, 0x73, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x69,
	0x6d, 0x70, 0x62, 0x22, 0x94, 0x01, 0x0a, 0x0a, 0x46, 0x65, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x7a, 0x65, 0x4f, 0x70, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x69, 0x7a, 0x65, 0x4f, 0x70, 0x22, 0x92, 0x01, 0x0a, 0x0a, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69,
	0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x6f, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x66, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x7a, 0x65, 0x4f,
	0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x69, 0x7a, 0x65, 0x4f, 0x70, 0x22,
	0x8d, 0x01, 0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x71,
	0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x71, 0x75,
	0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x69, 0x6d, 0x65, 0x22,
	0x7c, 0x0a, 0x0b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x23, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x69, 0x6d, 0x70, 0x62, 0x2e, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x32, 0x6a, 0x0a,
	0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x76, 0x63, 0x12, 0x2e, 0x0a, 0x05, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x12, 0x10, 0x2e, 0x69, 0x6d, 0x70, 0x62, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x1a, 0x11, 0x2e, 0x69, 0x6d, 0x70, 0x62, 0x2e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x05, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x12, 0x10, 0x2e, 0x69, 0x6d, 0x70, 0x62, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x1a, 0x11, 0x2e, 0x69, 0x6d, 0x70, 0x62, 0x2e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x42, 0x24, 0x0a, 0x18, 0x74, 0x65, 0x63,
	0x68, 0x2e, 0x66, 0x68, 0x79, 0x78, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x69, 0x6d, 0x73, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x06, 0x2e, 0x3b, 0x69, 0x6d, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_imsto_proto_rawDescOnce sync.Once
	file_imsto_proto_rawDescData = file_imsto_proto_rawDesc
)

func file_imsto_proto_rawDescGZIP() []byte {
	file_imsto_proto_rawDescOnce.Do(func() {
		file_imsto_proto_rawDescData = protoimpl.X.CompressGZIP(file_imsto_proto_rawDescData)
	})
	return file_imsto_proto_rawDescData
}

var file_imsto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_imsto_proto_goTypes = []interface{}{
	(*FetchInput)(nil),  // 0: impb.FetchInput
	(*ImageInput)(nil),  // 1: impb.ImageInput
	(*ImageMeta)(nil),   // 2: impb.ImageMeta
	(*ImageOutput)(nil), // 3: impb.ImageOutput
}
var file_imsto_proto_depIdxs = []int32{
	2, // 0: impb.ImageOutput.meta:type_name -> impb.ImageMeta
	0, // 1: impb.ImageSvc.Fetch:input_type -> impb.FetchInput
	1, // 2: impb.ImageSvc.Store:input_type -> impb.ImageInput
	3, // 3: impb.ImageSvc.Fetch:output_type -> impb.ImageOutput
	3, // 4: impb.ImageSvc.Store:output_type -> impb.ImageOutput
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_imsto_proto_init() }
func file_imsto_proto_init() {
	if File_imsto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_imsto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imsto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imsto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imsto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_imsto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_imsto_proto_goTypes,
		DependencyIndexes: file_imsto_proto_depIdxs,
		MessageInfos:      file_imsto_proto_msgTypes,
	}.Build()
	File_imsto_proto = out.File
	file_imsto_proto_rawDesc = nil
	file_imsto_proto_goTypes = nil
	file_imsto_proto_depIdxs = nil
}
