// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: imsto.proto

package impb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`   // APIKey
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`         // full URI of image
	Referer       string                 `protobuf:"bytes,3,opt,name=referer,proto3" json:"referer,omitempty"` // special referer of request
	Roof          string                 `protobuf:"bytes,4,opt,name=roof,proto3" json:"roof,omitempty"`       // section name
	UserID        int64                  `protobuf:"varint,5,opt,name=userID,proto3" json:"userID,omitempty"`  // user ID
	SizeOp        string                 `protobuf:"bytes,6,opt,name=sizeOp,proto3" json:"sizeOp,omitempty"`   // size op
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchInput) Reset() {
	*x = FetchInput{}
	mi := &file_imsto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchInput) ProtoMessage() {}

func (x *FetchInput) ProtoReflect() protoreflect.Message {
	mi := &file_imsto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchInput.ProtoReflect.Descriptor instead.
func (*FetchInput) Descriptor() ([]byte, []int) {
	return file_imsto_proto_rawDescGZIP(), []int{0}
}

func (x *FetchInput) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *FetchInput) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *FetchInput) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

func (x *FetchInput) GetRoof() string {
	if x != nil {
		return x.Roof
	}
	return ""
}

func (x *FetchInput) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *FetchInput) GetSizeOp() string {
	if x != nil {
		return x.SizeOp
	}
	return ""
}

type ImageInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`  // APIKey
	Image         []byte                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`    // Image Binary
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`      // FileName
	Roof          string                 `protobuf:"bytes,4,opt,name=roof,proto3" json:"roof,omitempty"`      // section name
	UserID        int64                  `protobuf:"varint,5,opt,name=userID,proto3" json:"userID,omitempty"` // user ID
	SizeOp        string                 `protobuf:"bytes,6,opt,name=sizeOp,proto3" json:"sizeOp,omitempty"`  // size op
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInput) Reset() {
	*x = ImageInput{}
	mi := &file_imsto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInput) ProtoMessage() {}

func (x *ImageInput) ProtoReflect() protoreflect.Message {
	mi := &file_imsto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInput.ProtoReflect.Descriptor instead.
func (*ImageInput) Descriptor() ([]byte, []int) {
	return file_imsto_proto_rawDescGZIP(), []int{1}
}

func (x *ImageInput) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ImageInput) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ImageInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageInput) GetRoof() string {
	if x != nil {
		return x.Roof
	}
	return ""
}

func (x *ImageInput) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ImageInput) GetSizeOp() string {
	if x != nil {
		return x.SizeOp
	}
	return ""
}

type ImageMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`     // 宽度
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`   // 高度
	Quality       int32                  `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"` // 质量（JPEG|WebP）
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`       // 大小
	Ext           string                 `protobuf:"bytes,5,opt,name=ext,proto3" json:"ext,omitempty"`          // 扩展名
	Mime          string                 `protobuf:"bytes,6,opt,name=mime,proto3" json:"mime,omitempty"`        // Mime type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageMeta) Reset() {
	*x = ImageMeta{}
	mi := &file_imsto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMeta) ProtoMessage() {}

func (x *ImageMeta) ProtoReflect() protoreflect.Message {
	mi := &file_imsto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMeta.ProtoReflect.Descriptor instead.
func (*ImageMeta) Descriptor() ([]byte, []int) {
	return file_imsto_proto_rawDescGZIP(), []int{2}
}

func (x *ImageMeta) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageMeta) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageMeta) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *ImageMeta) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImageMeta) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *ImageMeta) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

type ImageOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // 路径 id.ext
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`   // URI 地址
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"` // 主机名，取自 stagHost
	ID            string                 `protobuf:"bytes,4,opt,name=ID,proto3" json:"ID,omitempty"`     // ID 编码
	Meta          *ImageMeta             `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"` // 图片 Meta
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageOutput) Reset() {
	*x = ImageOutput{}
	mi := &file_imsto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageOutput) ProtoMessage() {}

func (x *ImageOutput) ProtoReflect() protoreflect.Message {
	mi := &file_imsto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageOutput.ProtoReflect.Descriptor instead.
func (*ImageOutput) Descriptor() ([]byte, []int) {
	return file_imsto_proto_rawDescGZIP(), []int{3}
}

func (x *ImageOutput) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ImageOutput) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ImageOutput) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ImageOutput) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ImageOutput) GetMeta() *ImageMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_imsto_proto protoreflect.FileDescriptor

const file_imsto_proto_rawDesc = "" +
	"\n" +
	"\vimsto.proto\x12\x04impb\"\x94\x01\n" +
	"\n" +
	"FetchInput\x12\x16\n" +
	"\x06apiKey\x18\x01 \x01(\tR\x06apiKey\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x18\n" +
	"\areferer\x18\x03 \x01(\tR\areferer\x12\x12\n" +
	"\x04roof\x18\x04 \x01(\tR\x04roof\x12\x16\n" +
	"\x06userID\x18\x05 \x01(\x03R\x06userID\x12\x16\n" +
	"\x06sizeOp\x18\x06 \x01(\tR\x06sizeOp\"\x92\x01\n" +
	"\n" +
	"ImageInput\x12\x16\n" +
	"\x06apiKey\x18\x01 \x01(\tR\x06apiKey\x12\x14\n" +
	"\x05image\x18\x02 \x01(\fR\x05image\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04roof\x18\x04 \x01(\tR\x04roof\x12\x16\n" +
	"\x06userID\x18\x05 \x01(\x03R\x06userID\x12\x16\n" +
	"\x06sizeOp\x18\x06 \x01(\tR\x06sizeOp\"\x8d\x01\n" +
	"\tImageMeta\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x18\n" +
	"\aquality\x18\x03 \x01(\x05R\aquality\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\x12\x10\n" +
	"\x03ext\x18\x05 \x01(\tR\x03ext\x12\x12\n" +
	"\x04mime\x18\x06 \x01(\tR\x04mime\"|\n" +
	"\vImageOutput\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x0e\n" +
	"\x02ID\x18\x04 \x01(\tR\x02ID\x12#\n" +
	"\x04meta\x18\x05 \x01(\v2\x0f.impb.ImageMetaR\x04meta2j\n" +
	"\bImageSvc\x12.\n" +
	"\x05Fetch\x12\x10.impb.FetchInput\x1a\x11.impb.ImageOutput\"\x00\x12.\n" +
	"\x05Store\x12\x10.impb.ImageInput\x1a\x11.impb.ImageOutput\"\x00B$\n" +
	"\x18tech.fhyx.platform.imstoP\x01Z\x06.;impbb\x06proto3"

var (
	file_imsto_proto_rawDescOnce sync.Once
	file_imsto_proto_rawDescData []byte
)

func file_imsto_proto_rawDescGZIP() []byte {
	file_imsto_proto_rawDescOnce.Do(func() {
		file_imsto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_imsto_proto_rawDesc), len(file_imsto_proto_rawDesc)))
	})
	return file_imsto_proto_rawDescData
}

var file_imsto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_imsto_proto_goTypes = []any{
	(*FetchInput)(nil),  // 0: impb.FetchInput
	(*ImageInput)(nil),  // 1: impb.ImageInput
	(*ImageMeta)(nil),   // 2: impb.ImageMeta
	(*ImageOutput)(nil), // 3: impb.ImageOutput
}
var file_imsto_proto_depIdxs = []int32{
	2, // 0: impb.ImageOutput.meta:type_name -> impb.ImageMeta
	0, // 1: impb.ImageSvc.Fetch:input_type -> impb.FetchInput
	1, // 2: impb.ImageSvc.Store:input_type -> impb.ImageInput
	3, // 3: impb.ImageSvc.Fetch:output_type -> impb.ImageOutput
	3, // 4: impb.ImageSvc.Store:output_type -> impb.ImageOutput
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_imsto_proto_init() }
func file_imsto_proto_init() {
	if File_imsto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_imsto_proto_rawDesc), len(file_imsto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_imsto_proto_goTypes,
		DependencyIndexes: file_imsto_proto_depIdxs,
		MessageInfos:      file_imsto_proto_msgTypes,
	}.Build()
	File_imsto_proto = out.File
	file_imsto_proto_goTypes = nil
	file_imsto_proto_depIdxs = nil
}
