// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: imsto.proto

package impb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImageSvc_Fetch_FullMethodName = "/impb.ImageSvc/Fetch"
	ImageSvc_Store_FullMethodName = "/impb.ImageSvc/Store"
)

// ImageSvcClient is the client API for ImageSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageSvcClient interface {
	// Fetch
	Fetch(ctx context.Context, in *FetchInput, opts ...grpc.CallOption) (*ImageOutput, error)
	// Store
	Store(ctx context.Context, in *ImageInput, opts ...grpc.CallOption) (*ImageOutput, error)
}

type imageSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewImageSvcClient(cc grpc.ClientConnInterface) ImageSvcClient {
	return &imageSvcClient{cc}
}

func (c *imageSvcClient) Fetch(ctx context.Context, in *FetchInput, opts ...grpc.CallOption) (*ImageOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageOutput)
	err := c.cc.Invoke(ctx, ImageSvc_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageSvcClient) Store(ctx context.Context, in *ImageInput, opts ...grpc.CallOption) (*ImageOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageOutput)
	err := c.cc.Invoke(ctx, ImageSvc_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageSvcServer is the server API for ImageSvc service.
// All implementations must embed UnimplementedImageSvcServer
// for forward compatibility.
type ImageSvcServer interface {
	// Fetch
	Fetch(context.Context, *FetchInput) (*ImageOutput, error)
	// Store
	Store(context.Context, *ImageInput) (*ImageOutput, error)
	mustEmbedUnimplementedImageSvcServer()
}

// UnimplementedImageSvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageSvcServer struct{}

func (UnimplementedImageSvcServer) Fetch(context.Context, *FetchInput) (*ImageOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedImageSvcServer) Store(context.Context, *ImageInput) (*ImageOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedImageSvcServer) mustEmbedUnimplementedImageSvcServer() {}
func (UnimplementedImageSvcServer) testEmbeddedByValue()                  {}

// UnsafeImageSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageSvcServer will
// result in compilation errors.
type UnsafeImageSvcServer interface {
	mustEmbedUnimplementedImageSvcServer()
}

func RegisterImageSvcServer(s grpc.ServiceRegistrar, srv ImageSvcServer) {
	// If the following call panics, it indicates UnimplementedImageSvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageSvc_ServiceDesc, srv)
}

func _ImageSvc_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageSvcServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageSvc_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageSvcServer).Fetch(ctx, req.(*FetchInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageSvc_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageSvcServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageSvc_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageSvcServer).Store(ctx, req.(*ImageInput))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageSvc_ServiceDesc is the grpc.ServiceDesc for ImageSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "impb.ImageSvc",
	HandlerType: (*ImageSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _ImageSvc_Fetch_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _ImageSvc_Store_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "imsto.proto",
}
