// Code generated by protoc-gen-go. DO NOT EDIT.
// source: imsto.proto

package impb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FetchInput struct {
	ApiKey               string   `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Uri                  string   `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Referer              string   `protobuf:"bytes,3,opt,name=referer,proto3" json:"referer,omitempty"`
	Roof                 string   `protobuf:"bytes,4,opt,name=roof,proto3" json:"roof,omitempty"`
	UserID               int64    `protobuf:"varint,5,opt,name=userID,proto3" json:"userID,omitempty"`
	SizeOp               string   `protobuf:"bytes,6,opt,name=sizeOp,proto3" json:"sizeOp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchInput) Reset()         { *m = FetchInput{} }
func (m *FetchInput) String() string { return proto.CompactTextString(m) }
func (*FetchInput) ProtoMessage()    {}
func (*FetchInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc4ef999971de385, []int{0}
}

func (m *FetchInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchInput.Unmarshal(m, b)
}
func (m *FetchInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchInput.Marshal(b, m, deterministic)
}
func (m *FetchInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchInput.Merge(m, src)
}
func (m *FetchInput) XXX_Size() int {
	return xxx_messageInfo_FetchInput.Size(m)
}
func (m *FetchInput) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchInput.DiscardUnknown(m)
}

var xxx_messageInfo_FetchInput proto.InternalMessageInfo

func (m *FetchInput) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *FetchInput) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *FetchInput) GetReferer() string {
	if m != nil {
		return m.Referer
	}
	return ""
}

func (m *FetchInput) GetRoof() string {
	if m != nil {
		return m.Roof
	}
	return ""
}

func (m *FetchInput) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *FetchInput) GetSizeOp() string {
	if m != nil {
		return m.SizeOp
	}
	return ""
}

type ImageInput struct {
	ApiKey               string   `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Image                []byte   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Roof                 string   `protobuf:"bytes,4,opt,name=roof,proto3" json:"roof,omitempty"`
	UserID               int64    `protobuf:"varint,5,opt,name=userID,proto3" json:"userID,omitempty"`
	SizeOp               string   `protobuf:"bytes,6,opt,name=sizeOp,proto3" json:"sizeOp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageInput) Reset()         { *m = ImageInput{} }
func (m *ImageInput) String() string { return proto.CompactTextString(m) }
func (*ImageInput) ProtoMessage()    {}
func (*ImageInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc4ef999971de385, []int{1}
}

func (m *ImageInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageInput.Unmarshal(m, b)
}
func (m *ImageInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageInput.Marshal(b, m, deterministic)
}
func (m *ImageInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageInput.Merge(m, src)
}
func (m *ImageInput) XXX_Size() int {
	return xxx_messageInfo_ImageInput.Size(m)
}
func (m *ImageInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageInput.DiscardUnknown(m)
}

var xxx_messageInfo_ImageInput proto.InternalMessageInfo

func (m *ImageInput) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *ImageInput) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *ImageInput) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ImageInput) GetRoof() string {
	if m != nil {
		return m.Roof
	}
	return ""
}

func (m *ImageInput) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *ImageInput) GetSizeOp() string {
	if m != nil {
		return m.SizeOp
	}
	return ""
}

type ImageMeta struct {
	Width                int32    `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Quality              int32    `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	Size                 int32    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Ext                  string   `protobuf:"bytes,5,opt,name=ext,proto3" json:"ext,omitempty"`
	Mime                 string   `protobuf:"bytes,6,opt,name=mime,proto3" json:"mime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageMeta) Reset()         { *m = ImageMeta{} }
func (m *ImageMeta) String() string { return proto.CompactTextString(m) }
func (*ImageMeta) ProtoMessage()    {}
func (*ImageMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc4ef999971de385, []int{2}
}

func (m *ImageMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageMeta.Unmarshal(m, b)
}
func (m *ImageMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageMeta.Marshal(b, m, deterministic)
}
func (m *ImageMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageMeta.Merge(m, src)
}
func (m *ImageMeta) XXX_Size() int {
	return xxx_messageInfo_ImageMeta.Size(m)
}
func (m *ImageMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ImageMeta proto.InternalMessageInfo

func (m *ImageMeta) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ImageMeta) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ImageMeta) GetQuality() int32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func (m *ImageMeta) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ImageMeta) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

func (m *ImageMeta) GetMime() string {
	if m != nil {
		return m.Mime
	}
	return ""
}

type ImageOutput struct {
	Path                 string     `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Uri                  string     `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Host                 string     `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	ID                   string     `protobuf:"bytes,4,opt,name=ID,proto3" json:"ID,omitempty"`
	Meta                 *ImageMeta `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ImageOutput) Reset()         { *m = ImageOutput{} }
func (m *ImageOutput) String() string { return proto.CompactTextString(m) }
func (*ImageOutput) ProtoMessage()    {}
func (*ImageOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc4ef999971de385, []int{3}
}

func (m *ImageOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageOutput.Unmarshal(m, b)
}
func (m *ImageOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageOutput.Marshal(b, m, deterministic)
}
func (m *ImageOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageOutput.Merge(m, src)
}
func (m *ImageOutput) XXX_Size() int {
	return xxx_messageInfo_ImageOutput.Size(m)
}
func (m *ImageOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ImageOutput proto.InternalMessageInfo

func (m *ImageOutput) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ImageOutput) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *ImageOutput) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ImageOutput) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ImageOutput) GetMeta() *ImageMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*FetchInput)(nil), "impb.FetchInput")
	proto.RegisterType((*ImageInput)(nil), "impb.ImageInput")
	proto.RegisterType((*ImageMeta)(nil), "impb.ImageMeta")
	proto.RegisterType((*ImageOutput)(nil), "impb.ImageOutput")
}

func init() {
	proto.RegisterFile("imsto.proto", fileDescriptor_bc4ef999971de385)
}

var fileDescriptor_bc4ef999971de385 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xb1, 0xaf, 0xd3, 0x30,
	0x10, 0xc6, 0x49, 0x9b, 0x04, 0x72, 0x45, 0xf0, 0xb0, 0x10, 0xb2, 0x98, 0x9e, 0x02, 0xc3, 0x9b,
	0x3c, 0x3c, 0x46, 0x36, 0x54, 0x21, 0x45, 0x08, 0x15, 0xb9, 0x1b, 0x9b, 0x5b, 0x2e, 0x8d, 0x51,
	0x5d, 0x07, 0xc7, 0x81, 0x16, 0xf1, 0x2f, 0xb0, 0x20, 0xfe, 0x60, 0x74, 0x97, 0x84, 0x32, 0x54,
	0x4c, 0x6f, 0xfb, 0xbe, 0xcb, 0x67, 0xdf, 0x2f, 0xe7, 0x83, 0x85, 0x75, 0x5d, 0xf4, 0xaa, 0x0d,
	0x3e, 0x7a, 0x91, 0x5a, 0xd7, 0x6e, 0xca, 0xdf, 0x09, 0xc0, 0x5b, 0x8c, 0xdb, 0xa6, 0x3a, 0xb4,
	0x7d, 0x14, 0xcf, 0x20, 0x37, 0xad, 0x7d, 0x87, 0x27, 0x99, 0x5c, 0x27, 0x37, 0x85, 0x1e, 0x9d,
	0xb8, 0x82, 0x79, 0x1f, 0xac, 0x9c, 0x71, 0x91, 0xa4, 0x90, 0x70, 0x3f, 0x60, 0x8d, 0x01, 0x83,
	0x9c, 0x73, 0x75, 0xb2, 0x42, 0x40, 0x1a, 0xbc, 0xaf, 0x65, 0xca, 0x65, 0xd6, 0x74, 0x6f, 0xdf,
	0x61, 0xa8, 0x96, 0x32, 0xbb, 0x4e, 0x6e, 0xe6, 0x7a, 0x74, 0x54, 0xef, 0xec, 0x77, 0x5c, 0xb5,
	0x32, 0x1f, 0xfa, 0x0d, 0xae, 0xfc, 0x95, 0x00, 0x54, 0xce, 0xec, 0xf0, 0xff, 0x58, 0x4f, 0x21,
	0xb3, 0x94, 0x62, 0xb0, 0x87, 0x7a, 0x30, 0x04, 0x70, 0x30, 0x0e, 0x47, 0x2e, 0xd6, 0x77, 0x02,
	0xf5, 0x33, 0x81, 0x82, 0xa1, 0xde, 0x63, 0x34, 0xd4, 0xfb, 0x9b, 0xfd, 0x14, 0x1b, 0x46, 0xca,
	0xf4, 0x60, 0xe8, 0x6c, 0x83, 0x76, 0xd7, 0x44, 0x46, 0xca, 0xf4, 0xe8, 0x68, 0x5c, 0x5f, 0x7a,
	0xb3, 0xb7, 0xf1, 0xc4, 0x58, 0x99, 0x9e, 0x2c, 0x91, 0xd1, 0xfd, 0x4c, 0x96, 0x69, 0xd6, 0x34,
	0x6e, 0x3c, 0x46, 0xc6, 0x2a, 0x34, 0x49, 0x4a, 0x39, 0xeb, 0x70, 0x24, 0x62, 0x5d, 0xfe, 0x80,
	0x05, 0xe3, 0xac, 0xfa, 0x48, 0x43, 0x12, 0x90, 0xb6, 0x66, 0xe4, 0x29, 0x34, 0xeb, 0x0b, 0xef,
	0x26, 0x20, 0x6d, 0x7c, 0x17, 0xa7, 0xe1, 0x90, 0x16, 0x8f, 0x60, 0x56, 0x2d, 0xc7, 0xd1, 0xcc,
	0xaa, 0xa5, 0x78, 0x01, 0xa9, 0xc3, 0x68, 0xb8, 0xff, 0xe2, 0xf6, 0xb1, 0xa2, 0x4d, 0x51, 0x7f,
	0xff, 0x5c, 0xf3, 0xc7, 0xdb, 0xcf, 0xf0, 0x80, 0x4b, 0xeb, 0xaf, 0x5b, 0xa1, 0x20, 0xe3, 0x25,
	0x12, 0x57, 0x43, 0xf6, 0xbc, 0x51, 0xcf, 0x9f, 0xfc, 0x73, 0x7a, 0x00, 0x2d, 0xef, 0x51, 0x7e,
	0x1d, 0x7d, 0xc0, 0x29, 0x7f, 0x7e, 0xea, 0x8b, 0xf9, 0x37, 0x2f, 0x41, 0x46, 0xdc, 0x36, 0xaa,
	0x6e, 0x4e, 0x47, 0xd5, 0xee, 0x4d, 0xac, 0x7d, 0x70, 0x8a, 0xb7, 0xf9, 0x43, 0xf2, 0x31, 0x57,
	0xaf, 0xe9, 0xcc, 0x26, 0xe7, 0xc5, 0x7e, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0x31, 0xa6, 0xc5,
	0x85, 0xe7, 0x02, 0x00, 0x00,
}
